
@url = http://localhost

###
post {{url}}/clientes-facturacion
Content-Type: application/json

{
    "clientes": [
        {
            "id": 12,
            "nombre": "Maria Jose",
            "apellido": "Elizondo Mera",
            "edad": 22,
            "domicilio": "Calle 10 de Agosto y Sandia"
        }
    ],
    "totalFacturas": 12400
}
